### ISSUE TITLE
Use requirejs to load esrileaflet and proj4leaflet  throws error

### ISSUE THREAD

**Issue by JackBaoL** [Esri/esri-leaflet-requirejs-example#1]
leaflet:  version  1.1.0
esrileaflet:  version 2.1.0
proj4:  version 2.4.3
proj4leaflet: version 1.0.1

I  have problem use  requirejs to load leaflet ,esrileaflet ,proj4 and proj4leaflet.

After loading reference model,the tiledMapLayer can show correct，but dynamicMapLayer can not display correct and throws a error  "proj4 is not defined" ,then i use  "window.proj4=proj4" to solve this problem.But the dynamicMapLayer  still can not show,and throws another problem when first image add to dynamicMapLayer.But when i use <script> to add reference model,everything is fine.

The spatialreference of this layer is epsg:2364,i test another map service(epsg:4326) , it throws same error.

**Comment by jgravois** [comment]
i just pushed up a sample which shows how to load proj4/proj4leaflet in requirejs for you to take a look at in a new branch called [`proj4`](https://github.com/Esri/esri-leaflet-requirejs-example/blob/proj4/app.js#L3-L20)

if this doesn't help you resolve your error, please provide a reproducible test case of your own with the bare minimum code necessary to demonstrate the problem. i'd be happy to take a look.

**Comment by JackBaoL** [comment]
Thank you for your answer sincerely.I think i found my problem,first time, i use requirejs to load leafleat.css,then browser throws a error
![image](https://user-images.githubusercontent.com/24949781/28901878-e42ef28e-782d-11e7-9f52-81db6a446cbc.png)
I debug the code, it occurs  when the first image requert successfully from server and were  added to dynamicMapLayer .

But If i load css file by <link> tag ,the dynamicMapLayer  shows correct.

 ```
require.config({
	baseUrl:"javascript/extra/api/",
	map: {
        "*": {
            "css": "require/css.min"
        }
      },
	  paths:{
	        "lealeft": "leaflet-src",
	        "esri-leaflet":"esri-leaflet/dist/esri-leaflet",
	        "proj4":"proj4/proj4",
	        "proj4leaflet":"proj4/proj4leaflet"
	  },
	  shim : {
	        "lealeft":["css!./leaflet"]
	  }
 });
define(['lealeft','esri-leaflet','proj4','proj4leaflet'],
	 function(leaflet,esri,proj4,Proj){
	    window.proj4=proj4;
	    var crs = new Proj.CRS('EPSG:27700', '+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs', {
	        origin: [-5220400.0, 4470200.0],
	        resolutions: [
	          132291.9312505292,
	          66145.9656252646,
	          26458.386250105836,
	          19843.789687579378,
	          13229.193125052918,
	          6614.596562526459,
	          2645.8386250105837,
	          1322.9193125052918,
	          661.4596562526459,
	          264.5838625010584,
	          132.2919312505292,
	          66.1459656252646,
	          26.458386250105836,
	          19.843789687579378,
	          13.229193125052918,
	          6.614596562526459,
	          2.6458386250105836,
	          1.3229193125052918,
	          0.6614596562526459
	        ]

	      });

	      var map = L.map('map', {
	        crs: crs
	      }).setView([53.386, -2.319], 7);

	      // The min/maxZoom values provided should match the actual cache thats been published. This information can be retrieved from the service endpoint directly.
	      esri.tiledMapLayer({
	        url: 'https://tiles.arcgis.com/tiles/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_Open_Background_2/MapServer',
	        maxZoom: 19,
	        minZoom: 6,
	      }).addTo(map);

	      // Dynamic map layers are projected by ArcGIS Server itself before the image is retrieved
	      esri.dynamicMapLayer({
	        url: "https://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer",
	        layers: [0],
	        opacity: 0.4
	      }).addTo(map);
});

```

**Comment by jgravois** [comment]
glad to hear it!
